add_lunch_combo pa_d2att-userdebug
add_lunch_combo pa_d2tmo-userdebug
add_lunch_combo pa_i605-userdebug
add_lunch_combo pa_i9300-userdebug
add_lunch_combo pa_l900-userdebug
add_lunch_combo pa_n7100-userdebug
