# CAF
add_lunch_combo pa_bacon-userdebug
add_lunch_combo pa_gemini-userdebug
add_lunch_combo pa_oneplus2-userdebug
add_lunch_combo pa_oneplus3-userdebug
add_lunch_combo pa_onyx-userdebug
add_lunch_combo pa_r7plus-userdebug
add_lunch_combo pa_trltexx-userdebug
add_lunch_combo pa_titan-userdebug
add_lunch_combo pa_robin-userdebug
add_lunch_combo pa_mido-userdebug

# Samsung Exynos devices
add_lunch_combo pa_gts210ltexx-userdebug
add_lunch_combo pa_gts210wifi-userdebug

# AOSP
add_lunch_combo pa_angler-userdebug
add_lunch_combo pa_bullhead-userdebug
add_lunch_combo pa_marlin-userdebug
add_lunch_combo pa_sailfish-userdebug
