# Nexus
add_lunch_combo pa_bullhead-userdebug
add_lunch_combo pa_angler-userdebug
add_lunch_combo pa_deb-userdebug
add_lunch_combo pa_grouper-userdebug
add_lunch_combo pa_flo-userdebug
add_lunch_combo pa_flounder-userdebug
add_lunch_combo pa_hammerhead-userdebug
add_lunch_combo pa_shamu-userdebug
add_lunch_combo pa_tilapia-userdebug
add_lunch_combo pa_mako-userdebug
add_lunch_combo pa_manta-userdebug

# Sony Yukon Platform
add_lunch_combo pa_eagle-userdebug
add_lunch_combo pa_flamingo-userdebug
add_lunch_combo pa_seagull-userdebug
add_lunch_combo pa_tianchi-userdebug

# Sony Rhine Platform
add_lunch_combo pa_amami-userdebug
add_lunch_combo pa_honami-userdebug
add_lunch_combo pa_togari-userdebug

# Sony Shinano Platform
add_lunch_combo pa_aries-userdebug
add_lunch_combo pa_castor-userdebug
add_lunch_combo pa_castor_windy-userdebug
add_lunch_combo pa_leo-userdebug
add_lunch_combo pa_scorpion-userdebug
add_lunch_combo pa_scorpion_windy-userdebug
add_lunch_combo pa_sirius-userdebug

# Sony Kitakami Platform
add_lunch_combo pa_ivy-userdebug
add_lunch_combo pa_karin-userdebug
add_lunch_combo pa_karin_windy-userdebug
add_lunch_combo pa_sumire-userdebug
add_lunch_combo pa_suzuran-userdebug

# CAF
add_lunch_combo pa_bacon-userdebug
add_lunch_combo pa_oneplus2-userdebug
add_lunch_combo pa_oneplus3-userdebug
add_lunch_combo pa_onyx-userdebug
add_lunch_combo pa_r7plus-userdebug
add_lunch_combo pa_trltexx-userdebug
add_lunch_combo pa_titan-userdebug
